# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: GraFx Docs
theme:
  name: material
  features:
    - navigation.tabs
  font:
    text: Ubuntu
  palette:
    primary: grey

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

    
extra_css:
  - stylesheets/extra.css  

nav:
    - Home: 'index.md'
    - 'CHILI GraFx':
        - 'Setting up CHILI GraFx':             'CHILI_GraFx/setup.md'
        - 'Migrating from My CHILI publish':    'CHILI_GraFx/mycpmigration.md'
        - 'Platform Admin':                     'CHILI_GraFx/admin.md'
        - 'Application overview':
            - 'Panel 1' :                       'CHILI_GraFx/panel1.md'
            - 'Panel 2' :                       'CHILI_GraFx/panel2.md'
        - 'How to':
            - 'Create a new environment' :      'CHILI_GraFx/how_to/create_environment.md'
            - 'Add media to GraFx' :            'CHILI_GraFx/how_to/add_media.md'
        - 'Integrate CHILI GraFx':
            - 'Getting started' :              'CHILI_GraFx/integration/getting_started.md'
            - 'Hello World' :                   'CHILI_GraFx/integration/hello_world.md'
        - 'Release notes':                      'CHILI_GraFx/releasenotes.md'
    - 'GraFx publisher':
        - 'The manual':                         'GraFx_publisher/manual.md'
        - 'Integration':                        'GraFx_publisher/integration.md'
        - 'Knowledge Base':                     'GraFx_publisher/knowledge_base.md'
        - 'Release notes':                      
            - 'GraFX publisher 2022':           'GraFx_publisher/grafxpublisher_2022.md'
            - 'GraFX publisher 2022 RC':        'GraFx_publisher/grafxpublisher_2022_rc.md'
            - 'GraFX publisher 2021':           'GraFx_publisher/grafxpublisher_2021.md'
            - 'GraFX publisher 2020.2':         'GraFx_publisher/grafxpublisher_2020_2.md'
            - 'GraFX publisher 2020.1':         'GraFx_publisher/grafxpublisher_2020_1.md'
    - 'GraFx studio':
        - 'Setting up GraFx studio':            'GraFx_studio/setup.md'
        - 'Application overview':
            - 'Layers':                         'GraFx_studio/layers.md'
        - 'Designing GraFx studio documents'    :
            - 'Hello world':                    'GraFx_studio/hello_world.md'
            - 'Intro level template':           'GraFx_studio/intro_document.md'
            - 'Intermedate level template':     'GraFx_studio/intermediate_document.md'
            - 'Advanced template design':       'GraFx_studio/adcanced_document.md'
        - 'Extending GraFx studio':
            - 'GraFx studio INDD plugin' :      'GraFx_studio/plugin/studio_indesign.md'
            - 'GraFx studio AI plugin' :        'GraFx_studio/plugin/studio_ai.md'
        - 'Integrate GraFx studio':
            - 'Getting started' :               'GraFx_studio/integration/getting_started.md'
            - 'Hello World' :                   'GraFx_studio/integration/hello_world.md'
        - 'Release notes':                      'GraFx_studio/releasenotes.md'

    - 'On-prem':
        - 'My CHILI publish':                   'on-premise/mycp.md'
        - 'CHILI publisher':                    'on-premise/chili_publisher.md'